[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# where PACKAGENAME and PACKAGEVERSION are the name and version of your package respectively.
[project]
name = "maze"
version = "1.0" 

[pytest]
testpaths = "tests/"

[tool.pytest.ini_options]
pythonpath = "."
